name: build container
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: build only-feet-cloud-ctf-tools
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build an image from Dockerfile
        run: |
          cd docker && make build
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/devsecfranklin/only-feet-cloud-ctf-tools:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
